name: CI
on:
  push:
  pull_request:
    branches:
      - master

  workflow_dispatch:

env:
  CACHIX_REPO: onsails-oss

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: ${{ env.CACHIX_REPO }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: test
        run: |-
          nix build -j auto --print-build-logs .#rustTest
          nix run nixpkgs#cargo-nextest -- nextest run --archive-file result/archive.tar.zst --workspace-remap .
        env:
          # NEXTEST_PROFILE: ci
          OPTIMISM_URL: ${{ secrets.OPTIMISM_URL }}
          ARBITRUM_URL: ${{ secrets.ARBITRUM_URL }}
          ETHEREUM_URL: ${{ secrets.ETHEREUM_URL }}
          POLYGON_URL: ${{ secrets.POLYGON_URL }}

  udeps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix-path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: ${{ env.CACHIX_REPO }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - name: udeps
        run: |-
          nix develop --command cargo-udeps udeps
